version: '3.9'

volumes:
  db:
  server:

networks:
  tp-network:

services:
  db:
    image: mariadb:10.5
    container_name: mariadb-container
    restart: always
    networks:
      - tp-network
    volumes:
      - db:/lib/mariadb/data
    environment:
      - MARIADB_DATABASE=articles_database
      - MARIADB_USER=articles
      - MARIADB_PASSWORD=fXcderT543--T(43
      - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=yes
    expose:
      - 3306
    ports:
      - 3306:3306
  backend:
    image: elodiesyg/django-tp:latest
    container_name: django-container
    command: python manage.py runserver
    volumes:
      - server:/lib/django/
    restart: always
    networks:
      - tp-network
    expose:
      - 8000
    ports:
      - 8000:8000
    depends_on:
      - db
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-container
    restart: always
    expose:
      - 8080
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
    networks:
      - tp-network
    depends_on:
      - db